name: libnpengine builder
run-name: Build ${{ github.ref_name }}

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'sg-*'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        packages: >
          boost-dev
          boost1.84-static
          make
          cmake
          clang
          git
          sdl2-dev
          pango-dev
          cairo-dev

    - name: install apk
      run: |
        wget https://github.com/Madagambada/libnpa/releases/download/libnpa-0.5.3/libnpa-0.5.3-r0.apk
        wget https://github.com/Madagambada/libnpa/releases/download/libnpa-0.5.3/libnpa-dev-0.5.3-r0.apk
        wget https://github.com/Madagambada/libnpengine/releases/download/libnpengine-0.5.3/libnpengine-0.5.3-r0.apk
        wget https://github.com/Madagambada/libnpengine/releases/download/libnpengine-0.5.3/libnpengine-dev-0.5.3-r0.apk
        apk add --allow-untrusted libnpa-0.5.3-r0.apk libnpa-dev-0.5.3-r0.apk libnpengine-0.5.3-r0.apk libnpengine-dev-0.5.3-r0.apk
      shell: alpine.sh --root {0}

    - name: build sg
      run: |
        echo "::group::Configure"
        mkdir build
        cd build
        export CXX=clang++
        export CC=clang
        cmake -DCMAKE_BUILD_TYPE=Release ..
        echo "::endgroup::"
        echo "::group::Build"
        make -j4
        echo "::endgroup::"
        doas make install
        doas cpack
      shell: alpine.sh {0}