name: libnpengine builder
run-name: Build ${{ github.ref_name }}

on:
  push:
    tags:
      - 'steins-gate-*'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        packages: >
          boost-dev
          make
          cmake
          clang
          git
          libpng-dev
          libpng-static
          sdl2-dev
          pango-dev
          cairo-dev
          cairo-static
          harfbuzz-static

    - name: install apk
      run: |
        wget https://github.com/Madagambada/libnpa/releases/download/libnpa-0.5.3/libnpa-0.5.3-r0.apk
        wget https://github.com/Madagambada/libnpa/releases/download/libnpa-0.5.3/libnpa-dev-0.5.3-r0.apk
        wget https://github.com/Madagambada/libnpengine/releases/download/libnpengine-0.5.3/libnpengine-0.5.3-r0.apk
        wget https://github.com/Madagambada/libnpengine/releases/download/libnpengine-0.5.3/libnpengine-dev-0.5.3-r0.apk
        apk add --allow-untrusted libnpa-0.5.3-r0.apk libnpa-dev-0.5.3-r0.apk libnpengine-0.5.3-r0.apk libnpengine-dev-0.5.3-r0.apk
      shell: alpine.sh --root {0}

    - name: build sg
      run: |
        echo "::group::Configure"
        mkdir build
        cd build
        export CXX=clang++
        export CC=clang
        cmake -DCMAKE_BUILD_TYPE=Release ..
        echo "::endgroup::"
        echo "::group::Build"
        make -j4
        echo "::endgroup::"
        doas make install
        doas cpack
      shell: alpine.sh {0}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        tag_name: ${{ github.ref }}
        files: /home/runner/work/steins-gate/steins-gate/build/${{ github.ref_name }}-Linux.tar.bz2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
